"""Add transfert fields to Profile

Revision ID: 1d7ee893dd2c
Revises: 7c8672de3eca
Create Date: 2025-06-26 14:56:24.324035

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d7ee893dd2c'
down_revision = '7c8672de3eca'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('voyage_destination', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('voyage_date_depart', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('voyage_date_retour', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('voyage_prix', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('voyage_statut', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('voyage_statut')
        batch_op.drop_column('voyage_prix')
        batch_op.drop_column('voyage_date_retour')
        batch_op.drop_column('voyage_date_depart')
        batch_op.drop_column('voyage_destination')

    # ### end Alembic commands ###
