"""Add assurance fields to Profile

Revision ID: 28f3e2c49929
Revises: 8bf58967a69c
Create Date: 2025-06-26 08:19:17.427758

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f3e2c49929'
down_revision = '8bf58967a69c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assurance_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('assurance_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('policy_number', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('start_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('end_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('coverage_details', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('coverage_details')
        batch_op.drop_column('end_date')
        batch_op.drop_column('start_date')
        batch_op.drop_column('policy_number')
        batch_op.drop_column('assurance_company')
        batch_op.drop_column('assurance_type')

    # ### end Alembic commands ###
