"""Add etudiant fields to Profile

Revision ID: 52ab34a7cb6a
Revises: 1d7ee893dd2c
Create Date: 2025-06-26 16:29:07.975964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52ab34a7cb6a'
down_revision = '1d7ee893dd2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('university_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('study_field', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('study_field')
        batch_op.drop_column('university_name')

    # ### end Alembic commands ###
