"""Add payment fields to profile

Revision ID: 770178750279
Revises: 
Create Date: 2025-06-13 01:09:18.758499

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '770178750279'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_paid', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_amount', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('service_completed', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('service_completed')
        batch_op.drop_column('total_amount')
        batch_op.drop_column('amount_paid')

    # ### end Alembic commands ###
