"""Initial migration

Revision ID: 8bf58967a69c
Revises: 
Create Date: 2025-06-23 07:29:51.254811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bf58967a69c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_name', sa.String(length=100), nullable=False),
    sa.Column('documents_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('nationality', sa.String(length=50), nullable=False),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.Column('cin', sa.String(length=50), nullable=True),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('custom_service', sa.String(length=100), nullable=True),
    sa.Column('photo_path', sa.String(length=200), nullable=True),
    sa.Column('documents_path', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_group', sa.Boolean(), nullable=True),
    sa.Column('amount_paid', sa.Float(), nullable=True),
    sa.Column('total_amount', sa.Float(), nullable=True),
    sa.Column('service_completed', sa.Boolean(), nullable=True),
    sa.Column('autocar_type', sa.String(length=50), nullable=True),
    sa.Column('seat_number', sa.String(length=20), nullable=True),
    sa.Column('departure_location', sa.String(length=100), nullable=True),
    sa.Column('arrival_location', sa.String(length=100), nullable=True),
    sa.Column('departure_date', sa.Date(), nullable=True),
    sa.Column('arrival_date', sa.Date(), nullable=True),
    sa.Column('bateau_type', sa.String(length=50), nullable=True),
    sa.Column('bateau_company', sa.String(length=100), nullable=True),
    sa.Column('departure_port', sa.String(length=100), nullable=True),
    sa.Column('arrival_port', sa.String(length=100), nullable=True),
    sa.Column('departure_date_bateau', sa.Date(), nullable=True),
    sa.Column('arrival_date_bateau', sa.Date(), nullable=True),
    sa.Column('cabin_number', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('group_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=50), nullable=False),
    sa.Column('last_name', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('passport', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['group_profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('hotel_booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('hotel_name', sa.String(length=100), nullable=True),
    sa.Column('check_in_date', sa.Date(), nullable=True),
    sa.Column('check_out_date', sa.Date(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('room_type', sa.String(length=50), nullable=True),
    sa.Column('booking_reference', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['profile_id'], ['profile.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hotel_booking')
    op.drop_table('group_member')
    op.drop_table('profile')
    op.drop_table('group_profile')
    # ### end Alembic commands ###
