"""Add hotel fields to Profile

Revision ID: c01ca8241045
Revises: 0382c31151f9
Create Date: 2025-06-13 18:55:15.966058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c01ca8241045'
down_revision = '0382c31151f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hotel_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('check_in_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('check_out_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('hotel_notes', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('profile', schema=None) as batch_op:
        batch_op.drop_column('hotel_notes')
        batch_op.drop_column('check_out_date')
        batch_op.drop_column('check_in_date')
        batch_op.drop_column('hotel_name')

    # ### end Alembic commands ###
